version: '2'
services:
  namenode:
    image: 'flokkr/hadoop-hdfs-namenode:latest'
    hostname: namenode
    ports:
      - '50070:50070'
      - '9870:9870'
    env_file:
      - ./compose-config
    environment:
      ENSURE_NAMENODE_DIR: /tmp/hadoop-hdfs/dfs/name
  datanode:
    image: 'flokkr/hadoop-hdfs-datanode:latest'
    env_file:
      - ./compose-config
  resourcemanager:
    image: 'jbourne/resourcemanager-experiment:latest'
    hostname: resourcemanager
    ports:
      - '8088:8088'
    env_file:
      - ./compose-config
    environment:
      - AWS_SECRET=${AWS_SECRET}
      - AWS_ACCESS=${AWS_ACCESS}
      - CONTAINER_SCALE=${CONTAINER_SCALE}
  nodemanager:
    image: 'flokkr/hadoop-yarn-nodemanager:latest'
    env_file:
      - ./compose-config
  historyserver:
    image: 'jbourne/hadoop-yarn-historyserver:latest'
    ports:
      - '19888:19888'
      - '8188:8188'
    env_file:
      - ./compose-config
